query myAcademicWorksPage($relativePath: String!) {
  academicWorksPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyAcademicWorksPageParts
  }
}

fragment MyAcademicWorksPageParts on AcademicWorksPage {
  __typename
  head {
    __typename
    title
    description
  }
  h1
}
