query myPublicAnthropologyPage($relativePath: String!) {
  publicAnthropologyPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyPublicAnthropologyPageParts
  }
}

fragment MyPublicAnthropologyPageParts on PublicAnthropologyPage {
  __typename
  head {
    __typename
    title
    description
  }
  h1
  intro
  reflectionsHeading
  reflectionsDescription
  interventionsHeading
  interventionsDescription
  interviewsHeading
  interviewsDescription
}
