query myPublicWorksPage($relativePath: String!) {
  publicWorksPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
      _values
    }
    ...MyPublicWorksPageParts
  }
}

fragment MyPublicWorksPageParts on PublicWorksPage {
  __typename
  head {
    __typename
    title
    description
  }
  h1
  intro
}
